# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='edgewise',
    version='0.0.1',
    author="Tyler Matteson",
    packages=setuptools.find_packages(),
    python_requires='>3.8'
)
