# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'readme.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='edgewise',
    version='0.1.0',
    description='An Active Record ORM for EdgeDB',
    python_requires='>=3.7.0',
    project_urls={"repository": "https://gitlab.com/agritheory/edgewise"},
    author='Tyler Matteson',
    author_email='tyler@agritheory.com',
    license='Apache License, Version 2.0',
    classifiers=[
        'Intended Audience :: Developers', 'Operating System :: OS Independent',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python'
    ],
    entry_points={
        "console_scripts": ["edgewise = edgwise.edgewise.cli:console"]
    },
    install_requires=[
        'attrs==19.*,>=19.3.0', 'edgedb==0.*,>=0.7.1',
        'python-dotenv==0.*,>=0.11.0'
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0", "ipython==7.*,>=7.12.0",
            "isort==4.*,>=4.3.21", "mypy==0.*,>=0.761.0", "pytest==4.*,>=4.6.0",
            "pytest-cov==2.*,>=2.8.1", "pytest-mypy==0.*,>=0.4.2",
            "tox==3.*,>=3.14.3", "typer==0.*,>=0.0.8"
        ]
    },
)
